version: '3.3'

services:
 notesqueue:
  image: nats
  ports:
   - "8222:8222"
  networks:
   - notesapp-net 

 notes-web:
  image: dockernotes/notes-web
  build:
   context: notes-web
  ports:
   - "80:80"
  depends_on:
   - notifications-service
   - processing-service
  networks:
   - notesapp-net
  env_file:
   - dockernotes.env

   
   
 notifications-service:
  image: dockernotes/notifications-service
  build:
   context: notifications-service
  ports:
   - "81:1234"
  depends_on:
   - notesqueue
  networks:
   - notesapp-net
  env_file:
   - dockernotes.env
   
 processing-service:
  image: dockernotes/processing-service
  build:
   context: processing-service
  depends_on:
   - notesqueue
   - notifications-service 
  networks:
   - notesapp-net
  env_file:
   - dockernotes.env
   
networks:
  notesapp-net:
    driver: nat
